version: "3.9"
services:
  gradebook:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./requirements.txt:/app/requirements.txt
      - ./app.py:/app/app.py
      - ./.streamlit:/app/.streamlit
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped